# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='business_unit',
        ),
        migrations.DeleteModel(
            name='BusinessUnit',
        ),
    ]
