# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20170101_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='projectname',
            name='asset',
        ),
        migrations.AddField(
            model_name='asset',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Application', verbose_name='\u4e1a\u52a1\u540d\u79f0'),
        ),
        migrations.AddField(
            model_name='asset',
            name='projectname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.Projectname', verbose_name='\u9879\u76ee\u540d\u79f0'),
        ),
    ]
