# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-01 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20170101_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='valid_begin_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='valid_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
