# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_auto_20170102_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='admin',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.UserProfile', verbose_name='\u8d44\u4ea7\u7ba1\u7406\u5458'),
        ),
    ]
