# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20170102_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='linkman',
            name='fixed_phone',
            field=models.IntegerField(default=12525468256L, max_length=20, verbose_name='\u5ea7\u673a'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linkman',
            name='memo',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='linkman',
            name='phone',
            field=models.IntegerField(max_length=20, verbose_name='\u624b\u673a'),
        ),
    ]
