# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20170103_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkman',
            name='fixed_phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u5ea7\u673a'),
        ),
        migrations.AlterField(
            model_name='linkman',
            name='phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u624b\u673a'),
        ),
    ]
