# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-04 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_auto_20170103_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='asset',
        ),
    ]
